### PR TITLE
fix(test): set hard version of core to avoid issue with setoutput

### PR DESCRIPTION
**Pull request by ThibDujardin**

### CODE REVIEW

**Comment by rlespinasse** [comment]
what is the issue related to this?

**Comment by ThibDujardin** [comment]
There is no issue related to this or I didn't found the one related to this.
This PR fix the "Operations testing" GA that fail on every build ( [jest test](https://github.com/sfeir-open-source/sfeir-school-github-action-dev/actions/workflows/operations-testing.yaml) ) 
It look like the `Core` library has made some change on the new version they made ( maybe it's a minor regression ) that make the `output::....` no longer appear on the stdout

**Comment by rlespinasse** [comment]
- https://github.com/actions/runner/pull/2118
- https://github.com/actions/toolkit/pull/1178

This will impact the slides on the `interactions` section as well

**Comment by rlespinasse** [comment]
https://github.com/actions/toolkit/security/advisories/GHSA-7r3h-m5j6-3q42

**Pull request merged**
